name: simple_deseq-env
dependencies:
  - python>=3.8.5
  - pip=20.2.2
  - pandas=1.5.3
  - scipy=1.
  - sklearn=1.0
  - joblib=1.4.2
  - statsmodels=
  - pip:
    - numpy>=1.22
    - pandas==1.5.3
    - scipy
    - sklearn==1.0
    - joblib==1.4.2
    - statsmodels